export const ACTIONS = Object.freeze({
  TASK_ADD: "TASK_ADD",
  TASK_TOGGLE_DONE: "TASK_TOGGLE_DONE",
  TASK_DELETE: "TASK_DELETE",
  TASK_EDIT: "TASK_EDIT",
  FAV_TOGGLE: "FAV_TOGGLE",
  FAV_CLEAR: "FAV_CLEAR",
  HYDRATE: "HYDRATE",
});
